### ISSUE TITLE
Spawning Prefabs example code causes error

### ISSUE THREAD

**Issue by kelden** [reeseschultz/ReeseUnityDemos#14]
This code:

```
[GenerateAuthoringComponent] // Auto-generates the actual conversion script.
struct PersonPrefab : IComponentData
{
    public Entity Value;
}
```

located at [Spawning Prefabs with Unity ECS | Reese Schultz](https://reeseschultz.com/spawning-prefabs-with-unity-ecs/), if copy-pasted by a naive pupil such as myself causes the [following error](https://issuetracker.unity3d.com/issues/entities-cannot-add-script-to-a-game-object-if-there-is-a-comment-after-generateauthoringcomponent) when you try to attach it to a game object:

"Can't add script behaviour <scriptName>. The script needs to derive from MonoBheaviour!"

Fix:

```
// Auto-generates the actual conversion script.
[GenerateAuthoringComponent]
struct PersonPrefab : IComponentData
{
    public Entity Value;
}
```

Thanks for the awesome tutorial btw :)

**Comment by reeseschultz** [comment]
Thank you! I went ahead and fixed that on my site. Sometimes I edit my own copy-pasted code just for the tutorials without going through the compiler, and this sort of thing happens.

FYI, that tutorial is actually out-of-sync with this project now, come to think of it. I still use the same strategy, but generalized the spawning to work for any prefab, and any combination of `IComponentData` and`IBufferElementData`. I turned it into a UPM package. You may read about it [here](https://github.com/reeseschultz/ReeseUnityDemos/tree/master/Packages/Spawning).

With the conversion to UPM packages, and work releasing [ubump](https://github.com/reeseschultz/ubump), my site's been neglected for about a month. In the coming days I'll update the affected tutorials accordingly, and write more posts.

Thanks again.
