### ISSUE TITLE
Upgrade to Entities 0.6.0

### ISSUE THREAD

**Issue by NickTaSpy** [reeseschultz/ReeseUnityDemos#16]
I tried the demo scene NavMovingJumpDemo with Entities 0.6.0 (latest version) and some exceptions occured like this one:

```
ArgumentException: The previously scheduled job NavInterpolationSystem:<>c__DisplayClass_NavArtificialGravityJob writes to the NativeArray <>c__DisplayClass_NavArtificialGravityJob.Data.commandBuffer. You must call JobHandle.Complete() on the job NavInterpolationSystem:<>c__DisplayClass_NavArtificialGravityJob, before you can write to the NativeArray safely.
EntityCommandBuffer was recorded in Reese.Nav.NavInterpolationSystem and played back in Unity.Entities.EndSimulationEntityCommandBufferSystem.
```

I found out I can fix these type of exceptions by adding the following line before I return a handle in the OnUpdate methods of the classes that are mentioned in the exception messages:

`barrier.AddJobHandleForProducer(handle);`

I am not very familiar with ECS or this project in particular but I decided to open this issue anyway to hear your thoughts.

**Comment by reeseschultz** [comment]
The project and nav package aren't presently supporting Unity.Entities `0.6.0`, but I'd be happy to upgrade it no later than this weekend (I'm busy ATM).

Reminds me that I need a better way to get alerts on updates. Something like [Greenkeeper](https://greenkeeper.io/) as a GitHub Action or something, but for Unity projects.

Anyway, thanks for letting me know—I appreciate that you took the time to look into this. I'll close this issue after I upgrade the project.
