### ISSUE TITLE
Add teleportation support

### ISSUE THREAD

**Issue by kobechenyang** [reeseschultz/ReeseUnityDemos#25]
Hi Reese.
I am a bit confused about how the Parent of NavAgent works. I can see you set the parent of NavAgent when you spawn the agent. Do I have to set the surface as parent of agents?
I have a case I need to teleport agents to a different surface. 
When the agents arrived at the new surface. I simply do 
```
commandBuffer.AddComponent(entityInQueryIndex, entity, new NavNeedsDestination
{
     Value = worldPoint
});
```
But that seems no good enough. I need to set the Parent of agents somehow? I don't see you set the Parent of agents in the example you provided. Can you help explain what I need to do?

**Comment by reeseschultz** [comment]
Hey @kobechenyang, parent surfaces always need to be set on agents, although that is intended only to be the responsibility of the nav package, ideally not user code.

I happen to be a proponent of teleportation. It's a special case,  and I believe I can add a feature to support it quite cleanly. I'll try to tackle this tonight or tomorrow, but in the meantime here's how I think you'll use it:

```csharp
commandBuffer.AddComponent(entityInQueryIndex, entity, new NavNeedsDestination
{
  Value = worldPoint,
  Teleport = true // New flag.
});
```

But! Notice that `Value`  loses its semantic meaning in that case, so actually I'll do a breaking change like so:

```csharp
commandBuffer.AddComponent(entityInQueryIndex, entity, new NavNeedsDestination
{
  Destination = worldPoint, // Value -> Destination
  Teleport = true
});
```
I'll do the teleportation work for you from there.

Changing `Value` to `Destination` is a breaking change; however, the nav code is effectively in a pre-release state, so breaking changes like that are acceptable for now IMO. I don't feel like deprecating `Value` and managing both variables is going to mess anyone up too bad. We all know how to find-and-replace, although after the first major release I'll deprecate things like a responsible adult.

**Comment by kobechenyang** [comment]
Cool ! That will be very helpful.

I also found out once I change the translation value Y of the surface. Somehow it breaks something. I set the surface Y to 100 and using agent offset to be 101 so it spawns correctly. But somehow it didn't find the target surface. Is that how I should use the offset value? 
![image](https://user-images.githubusercontent.com/8561346/84308607-a76eb480-ab13-11ea-9be8-edccec1f854c.png)

**Comment by reeseschultz** [comment]
I can absolutely look at that as well, although it's a separate issue. I'll open a different one.

**Comment by reeseschultz** [comment]
This issue is resolved, but haven't released the nav package yet—I'll do the release for both #25 and #26 sometime tomorrow.

**Comment by reeseschultz** [comment]
Actually I'll go ahead and release this now since I suggested a resolution to #26 that shouldn't need any modifications on my part.

**Comment by reeseschultz** [comment]
The `NavPointAndClick` demo scene now includes a toggle for teleportation so you can experiment with how it works. Hope this helps!

**Comment by kobechenyang** [comment]
Thank you ! I will try out the new version and let you know.

**Comment by kobechenyang** [comment]
Hi @reeseschultz  I just tried the newer version. Teleport works great for me ! You are awesome ! Thank you !
