### ISSUE TITLE
Project management thoughts

### ISSUE THREAD

**Issue by reeseschultz** [reeseschultz/ReeseUnityDemos#31]
I'm considering implementing a policy requiring either reproduction of issues via a publicly accessible repository, or, via pull request adding a new scene to support new test scenarios with corresponding fixes and additions. I may also require at least some investigation of the problem by folks submitting issues, beyond stating a problem exists. These are submission standards I intend to codify and publicize, because my time is precious.

Tangentially, I'll want to introduce a staleness bot since I will ignore issues that don't meet submission standards.

Another strong consideration of mine is integrating [Issuehunt](https://issuehunt.io/) or something like it.

Finally, it's been over six months since I created this repository, and I have yet to see a single PR from anyone other than myself. Now, I'm wondering if there's something I could do to encourage collaboration on a platform presumably designed for that purpose. It's possible I need documentation detailing system flow for the navigation package, for instance. I'd be happy to provide others with the resources they need to assist, but unfortunately I don't know what those resources are because nobody's asked for them.

**Comment by kobechenyang** [comment]
Hi, Reese. I am happy to help out. But I am new to ECS and learning all these stuff. We definitely appreciate the effort you put into this project. 
As I am learning the system more. I may able to contribute more down the road. I can help set up some demo scenes for instance.  Cheers !

**Comment by reeseschultz** [comment]
Thanks @kobechenyang, I appreciate your kind words. If there's anything you can think of that would ease collaboration, please share it in this issue.

**Comment by reeseschultz** [comment]
Update: I added a couple issue templates. I still need to add contributing guidelines.

**Comment by reeseschultz** [comment]
I added contributing guidelines *and* a code of conduct. But⁠—the contributing guidelines generally describe issues and pull requests, not working with any of the included packages specifically. I need to add documentation explaining the project structure and how to contribute to said packages.

**Comment by reeseschultz** [comment]
Eh, I think the work done is good enough for now. People are following the issue templates. Closing.
