### ISSUE TITLE
Nav: Control and finer approximation of when an agent reaches a destination

### ISSUE THREAD

**Issue by reeseschultz** [reeseschultz/ReeseUnityDemos#41]
**Is the improvement related to a problem? Please describe.**

Kind of, but I don't consider it a bug. Since reaching a destination is approximate, agents never truly reach the exact requested destination. They're supposed to just be *close*, but I have noticed that sometimes it doesn't look all that close.

**Describe the solution you'd prefer:**

The approximation needs to be controlled by users via a variable, not through hard-coding.

**Describe alternatives or workarounds you've considered:**

There are no reasonable alternatives or workarounds for this, aside from setting a destination ahead of the "true destination."

**Comment by roudikk** [comment]
Hey I've realized this issue when working on the project, it seems like it has the equivalent of `NavMeshAgent`'s stopping distance, or me it's always 1 Unit away from the destination and there is no way in `NavAgent` to change that. However it works when `Teleport = true` in `NavNeedsDestination`, the agent is exactly at the destination it should be at.
