### ISSUE TITLE
Nav: Replace the static class of constants with an actual configuration file

### ISSUE THREAD

**Issue by reeseschultz** [reeseschultz/ReeseUnityDemos#42]
**Is the improvement related to a problem? Please describe.**

Yeah, the problem is that, each time a user updates their nav package, the constants will be replaced. Users may well change these values, and then have them unknowingly replaced, which could cause hard-to-track-down bugs.

**Describe the solution you'd prefer:**

To override navigation settings at the user-level, there ought to be a configurable `NavWorld` and/or blob asset with reasonable defaults. This change will probably confuse preexisting users when they upgrade, but it's for the best.

**Describe alternatives or workarounds you've considered:**

I don't think the constants file has ever really been a good idea, honestly. I went with it at the beginning of this year because DOTS' lack of maturity (at the time) precluded the suggested solutions above.

**Comment by P-Stringer** [comment]
Hi, 

Is this change still on the cards? I'm trying to update `PATH_SEARCH_MAX` but since I'm using the package manager, everytime I save in my IDE and return to Unity it overwrites the changes. Is there a workaround that allows me to still use UPM or should I clone the package seperately?

Thanks.

**Comment by reeseschultz** [comment]
@P-Stringer Yes, the change is still in the cards. I'm not sure about a UPM-compatible workaround.

Do you have any ideas about how the configuration should work? Please let me know.

**Comment by P-Stringer** [comment]
@reeseschultz I don't actually - at least not any ideas better than you've probably already considered! I'm really new to DOTs and ECS so I'm not really sure what the best approach would be or what sort of standard the industry would expect. Maybe a virtual property in an abstract class that can be overriden with a default value? Or use some kind of ScriptableObject that holds the settings?

**Comment by reeseschultz** [comment]
Thanks for sharing your thoughts. I had considered a ScriptableObject for a while, but to be honest I've always found them unruly. Worse, [Deform](https://github.com/keenanwoodall/Deform) uses one for configuration and I encounter https://github.com/keenanwoodall/Deform/issues/33 any time I try to use it. Maybe it's because I'm running Linux. Who knows?

I see what you're angling at with virtual properties. That actually makes the most sense to me. I'm not a C# guru, I'm more of an opportunistic generalist, so the thought just didn't cross my mind :wink: . I can attempt that path and get back to you if it ends up making sense. I *think* it will.

**Comment by reeseschultz** [comment]
Oh, one thing I wanted to mention as well is that one constraint I have/had is that I need to avoid usage of static variables so [play mode can be entered quickly](https://forum.unity.com/threads/protip-super-fast-enter-playmode-times-when-working-in-dots.984543/). `feat/demo-overhaul` has fast-enter play mode turned on in the editor settings, but I don't believe the main branch has it.

**Comment by P-Stringer** [comment]
Ah ok noted.

Yeah I have to agree with your point about ScriptableObjects, often find myself fighting with them! I've quickly put together a possible solution. Takes a bit from your original idea of a `NavWorld`. Basically, a thread safe Singleton that has a Settings property with default values that can be overriden. I did it in my own project to quickly test but if you like the idea I can create a PR? Although it might need a bit of work because its making use of a static variable which you've mentioned you want to avoid. Either way, thought I'd share to see what you think.

The idea is it isn't too different to how you would change the settings currently and it makes use of the object initialisers pattern I've seen a lot with DOTS and ECS. Anyway code below

**NavWorld.cs**
```
 public class NavWord
    {
        private static readonly NavWord _current = new NavWord();
        public Settings Settings { get; set; } = new Settings();
        
        static NavWord()
        {
        }

        private NavWord()
        {
        }

        public static NavWord Current
        {
            get { return _current; }
        }
    }

    public class Settings
    {
        /// <summary>A sphere collider of the specified radius is used to detect the destination surface.</summary>
        public virtual float DestinationSurfaceColliderRadius { get; set; } = 1;

        /// <summary>Upper limit on the *duration* spent jumping before the agent is actually considered falling. This limit can be reached when the agent tries to jump too close to the edge of a surface and misses.</summary>
        public virtual float JumpSecondsMax { get; set; } = 5;

        /// <summary>Upper limit on the raycast distance when searching for an obstacle in front of a given NavAgent.</summary>
        public virtual float ObstacleRaycastDistanceMax { get; set; } = 1000;

        /// <summary>Upper limit on the raycast distance when searching for a surface below a given NavAgent.</summary>
        public virtual float SurfaceRaycastDistanceMax { get; set; } = 1000;

        /// <summary>The layer for surfaces.</summary>
        public virtual int SurfaceLayer { get; set; } = 28;

        /// <summary>The layer for obstacles.</summary>
        public virtual int ObstacleLayer { get; set; } = 29;

        /// <summary>The layer for colliders.</summary>
        public virtual int ColliderLayer { get; set; } = 30;

        /// <summary>Upper limit on the iterations performed in a NavMeshQuery to find a path in the NavPlanSystem.</summary>
        public virtual int IterationMax { get; set; } = 1000;

        /// <summary>Upper limit on a given jumpable surface buffer. Exceeding this merely results in allocation of heap memory.</summary>
        public virtual int JumpableSurfaceMax { get; set; } = 30;

        /// <summary>Upper limit on the path node pool size for each NavMeshQuery created in the NavMeshQuerySystem. May need to be increased if an OutOfNodes error arises while finding a path.</summary>
        public virtual int NavMeshQueryNodeMax { get; set; } = 5000;

        /// <summary>The initial capacity of the map tracking agents that need a surface.</summary>
        public virtual int NeedsSurfaceMapSize { get; set; } = 1000;

        /// <summary>Upper limit on a given path buffer. Exceeding this merely results in allocation of heap memory.</summary>
        public virtual int PathNodeMax { get; set; } = 1000;

        /// <summary>Upper limit on the search area size during path planning.</summary>
        public virtual int PathSearchMax { get; set; } = 1000;

        /// <summary>Upper limit on the number of raycasts to attempt in searching for a surface below the NavAgent. Exceeding this implies that there is no surface below the agent, its then determined to be falling which means that no more raycasts will be performed.</summary>
        public virtual int SurfaceRaycastMax { get; set; } = 100;

        /// <summary>The 'Humanoid' NavMesh agent type as a string.</summary>
        public const string HUMANOID = "Humanoid";
    }
```

Then to use it you would just do the following somewhere in your code

```
 NavWord.Current.Settings = new Settings
        {
            PathSearchMax = int.MaxValue
            // change any other settings you wish to...
        };
```

The only problem I can see with this approach is the settings could be changed at any point during play - I don't know what impact that might have inside your package code.

Anyway, let me know what you think. Like I say, this is just a quick scribble more than anything else.

**Comment by reeseschultz** [comment]
I appreciate you looking into this, and I think you're on the right track.

> Although it might need a bit of work because its making use of a static variable which you've mentioned you want to avoid.

Yeah, we must avoid the static variable. Here's an approach I prefer blending our thoughts:

```c#
using Unity.Entities;

namespace Reese.Nav
{
    public class NavSystem : SystemBase
    {
        public NavSettings Settings { get; set; } = new NavSettings();

        public class NavSettings
        {
            // Includes the properties you noted in the above comment.
        }

        protected override void OnUpdate() { }
    }
}
```

Thus, the settings are readable and writable via `NavSettings settings => World.GetOrCreateSystem<NavSystem>().Settings;`. Writing to that is essentially the same as what you're suggesting, I'm just partial to different conventions. Anyway, the user could then change the settings in a custom system that runs in the initialization group (which we can provide an example in the docs for), or even a MonoBehaviour for some reason if the default world was injected into it.

I like our combined approach including the `SystemBase` extension because it guarantees one `NavSystem` per [world](https://docs.unity3d.com/Packages/com.unity.entities@0.16/manual/world.html?q=world), in the strict sense, which also means one set of settings per world. It's straightforward because it just defaults to, well, the default world like all the other systems, unless the user specifies otherwise.

Further, even if the user technically disables the `NavSystem` for some insane reason, it still works, because all disabling it will accomplish is cutting off the `OnUpdate` method, which doesn't actually execute anything (it's required to be overridden as per the `SystemBase` as a formality).

As far as changing the properties in this manner goes, you mentioned:

> the settings could be changed at any point during play - I don't know what impact that might have inside your package code.

I was worried about that too, but feasibly the user could *correct* for issues determined at runtime by updating the settings. The `NavHasProblem` component could be used in that manner to increase/decrease things depending on the specific problem it reports for a given entity. A couple users in the past have encountered issues that may well call for this sort of solution. The flipside is, yes, someone will inevitably do something dumb. If they break their game because they have no idea what they're doing, the worst that will happen is that I will be entertained if/when they publicly post about it.

Finally, as to submitting a PR: you can if you want, but I can implement this today on `master` if you like now that I'm clear on the direction—thanks to you! Let me know what you prefer. I can deal with merging it into `feat/demo-overhaul` later—I can't let that branch block all other progress.

**Comment by P-Stringer** [comment]
Perfect - I like it! Nice work 😄 

Yeah I would definately prefer for you to do it if that's ok, that would be amazing.

Thanks for being so responsive with this and thanks again for such a brilliant package!

**Comment by reeseschultz** [comment]
Thanks, and you're welcome. I'll let you know when this is done.

**Comment by reeseschultz** [comment]
The refactor is nearly done. It's required some deviations from what was discussed above, but I think most people will be happy with the result. Only issue is that I'm noticing some agents getting stuck in the `NavTerrainDemo`. I need to do some testing to see what's happening with that. It could be that a value got mixed around or something.

After that, I'll create an override system in the demo code, not in the `nav` package, so that people can just easily copy-paste it or change it if forking this repo. Following that, an update to the docs. I'll do one big commit for it all.

**Comment by reeseschultz** [comment]
Looks like the bug was created by updating the editor and dependencies with 0331893e968346821a59794c2607b7cd9d17e98c, not the code needed for the settings. It's a minor bug that can be worked around by the user by effectively resetting agents that aren't translating like they should be, although it should be fixed in `feat/demo-overhaul`, since it has the same up-to-date dependencies and does not have the same problem. In that branch the interpolation logic was updated and optimized, so I'm not surprised. Not to mention the `NavTerrainDemo` is always the complainer so to speak.

Moving forward since the bug wasn't caused by these changes.

**Comment by P-Stringer** [comment]
Ah OK, that's good news then. You work fast! Looking forward to trying it out.

**Comment by reeseschultz** [comment]
@P-Stringer I work fast, but only when I work lol.

Okay, so the changes are in place as of nav/v0.14.0. You should be able to update the nav package via UPM to get it. Of course there's no changelog for it, because I guess [ubump](https://github.com/reeseschultz/ubump) is broken. :angry: Anyway...

Please see the documentation update [here](https://github.com/reeseschultz/ReeseUnityDemos/tree/nav#runtime-settings). Mind you, much of the other documentation is a little inaccurate, so it was updated in `feat/demo-overhaul` which hasn't been merged into `master` yet.

So as previously stated, I had to do things a little different. Here's how you can override settings:

```c#
namespace YourNamespace
{
    [UpdateInGroup(typeof(InitializationSystemGroup))]
    public class NavSettingsOverrides : SystemBase
    {
        NavSystem navSystem = default;

        protected override void OnCreate()
        {
            navSystem = World.GetOrCreateSystem<NavSystem>();

            navSystem.Settings = new NavSettings
            {
                DestinationSurfaceColliderRadius = 1,
                JumpSecondsMax = 5,
                ObstacleRaycastDistanceMax = 1000,
                SurfaceRaycastDistanceMax = 1000,
                SurfaceLayer = 28,
                ObstacleLayer = 29,
                ColliderLayer = 30,
                IterationMax = 1000,
                NavMeshQueryNodeMax = 0,
                NeedsSurfaceMapSize = 1000,
                PathSearchMax = 1000,
                SurfaceRaycastMax = 100
            };
        }

        protected override void OnUpdate() { }
    }
}
```

`NavSettings` is actually a struct. Here's how it and `NavSystem` were implemented:

```c#
using Unity.Entities;

namespace Reese.Nav
{
    /// </summary>System serving as the single source of truth of navigation settings.</summary>
    public class NavSystem : SystemBase
    {
        /// <summary>Settings that can be updated at runtime.</summary>
        public NavSettings Settings = new NavSettings {
            DestinationSurfaceColliderRadius = 1,
            JumpSecondsMax = 5,
            ObstacleRaycastDistanceMax = 1000,
            SurfaceRaycastDistanceMax = 1000,
            SurfaceLayer = 28,
            ObstacleLayer = 29,
            ColliderLayer = 30,
            IterationMax = 1000,
            NavMeshQueryNodeMax = 5000,
            NeedsSurfaceMapSize = 1000,
            PathSearchMax = 1000,
            SurfaceRaycastMax = 100
        };

        /// <summary>Includes settings used by the navigation systems.</summary>
        public struct NavSettings
        {
            /// <summary>A sphere collider of the specified radius is used to detect the destination surface.</summary>
            public float DestinationSurfaceColliderRadius;

            /// <summary>Upper limit on the *duration* spent jumping before the agent is actually considered falling. This limit can be reached when the agent tries to jump too close to the edge of a surface and misses.</summary>
            public float JumpSecondsMax;

            /// <summary>Upper limit on the raycast distance when searching for an obstacle in front of a given NavAgent.</summary>
            public float ObstacleRaycastDistanceMax;

            /// <summary>Upper limit on the raycast distance when searching for a surface below a given NavAgent.</summary>
            public float SurfaceRaycastDistanceMax;

            /// <summary>The layer for surfaces.</summary>
            public int SurfaceLayer;

            /// <summary>The layer for obstacles.</summary>
            public int ObstacleLayer;

            /// <summary>The layer for colliders.</summary>
            public int ColliderLayer;

            /// <summary>Upper limit on the iterations performed in a NavMeshQuery to find a path in the NavPlanSystem.</summary>
            public int IterationMax;

            /// <summary>Upper limit on the path node pool size for each NavMeshQuery created in the NavMeshQuerySystem. May need to be increased if an OutOfNodes error arises while finding a path.</summary>
            public int NavMeshQueryNodeMax;

            /// <summary>The initial capacity of the map tracking agents that need a surface.</summary>
            public int NeedsSurfaceMapSize;

            /// <summary>Upper limit on the search area size during path planning.</summary>
            public int PathSearchMax;

            /// <summary>Upper limit on the number of raycasts to attempt in searching for a surface below the NavAgent. Exceeding this implies that there is no surface below the agent, its then determined to be falling which means that no more raycasts will be performed.</summary>
            public int SurfaceRaycastMax;
        }

        protected override void OnUpdate() { }
    }
}
```

The struct is used so that it can be plopped directly into the navigation jobs, if you're wondering. I forgot I'd need to do it like that earlier. Technically this allows users to plop the `NavSettings` struct into their own jobs if needed.

I hope this helps!

**Comment by reeseschultz** [comment]
And thanks for your help, by the way!
