### ISSUE TITLE
Need to free pointers in NavMeshQuerySystem

### ISSUE THREAD

**Issue by wang37921** [reeseschultz/ReeseUnityDemos#44]
Need UnsafeUtility.Free NavMeshQueryPointer in NavMeshQuerySystem.OnDestroy?
![image](https://user-images.githubusercontent.com/1498324/96822885-b3716800-145d-11eb-94f5-51a5d074abc4.png)

**Comment by reeseschultz** [comment]
Yep, good catch. I'll fix this shortly.
