### ISSUE TITLE
Update docs and code to reflect logging support in Burst-compiled jobs

### ISSUE THREAD

**Issue by reeseschultz** [reeseschultz/ReeseUnityDemos#61]
Adding `UnityEngine` as an import and calling `WithoutBurst` in jobs is wearing my patience thin, as I've done it a bazillion times now when troubleshooting. It's also accident-prone.

Thus, I propose a Burst-compatible logging package. I'll think more about the API. I definitely want proper log levels handled in a concise and straightforward manner.

**Comment by Dreaming381** [comment]
I just saw this in the forums and went here to check if this was just an issue with using 2019.3. But it seems you are no longer using 2019.3.
As of the Unity versions supported by latest DOTS, Debug.Log and friends are supported in Bursted jobs. However, you must use string interpolation or String.Format for this to work (concatenating strings using the + operator is not supported).

**Comment by reeseschultz** [comment]
@Dreaming381 that's great to know, thanks for the heads-up. I'll update my docs to reflect that.
