### ISSUE TITLE
NavPathBuffer not cleared in after adding NavStop to Agent

### ISSUE THREAD

**Issue by ste-phil** [reeseschultz/ReeseUnityDemos#62]
**Bug description:**
After adding a new NavDestination to a currently lerping NavAgent there is the possibility the NavPathBuffer is not properly cleared from previous path, which leads to lerping to old NavDestination. Looks like this happens if you add NavStop and NavDestination shortly after each other.

**Bug reproduction:**
1. Apply NavDestination to agent
2. Apply StopNavigation to cancel movement
3. Apply new or same NavDestination to agent
4. Agent now lerps to new NavDestination but after it also lerps to old NavDestination because there are old path nodes in the NavPathBuffer

**Expected behavior:**
Should clear NavPathBuffer for previous destinations

**Describe alternatives or workarounds you've considered:**
I fixed the problem by clearing the NavPathBuffer in the NavStopSystem, but I dont know if this could lead to any side effects.
I could also provide a basic project with the issue, if it is not clear what is happening.

**Comment by reeseschultz** [comment]
This looks like an oversight in the nav package. Your workaround should be the correct solution. I'll fix this later today. Thanks for submitting this report @xXPancakeXx.

**Comment by reeseschultz** [comment]
@xXPancakeXx this was fixed in `nav/v0.20.1` with ea6c2b02104340cc2dc383ac8194bd06fed6e737. In addition to clearing the path buffer, I also needed to ensure the `NavStopSystem` runs after the `NavLerpSystem` to prevent conflicts.

**Comment by ste-phil** [comment]
Thanks 👍
