### ISSUE TITLE
Add automated linting and/or code formatting

### ISSUE THREAD

**Issue by reeseschultz** [reeseschultz/ReeseUnityDemos#72]
**Is the improvement related to a problem? Please describe.**

The project has grown to the point that even my own code is stylistically inconsistent with itself due to my mind changing about how it should read. As new collaborators join the fray, the issue will only be exacerbated. That's not really anybody's fault; this is just what happens when a project gets big enough.

**Describe the solution you'd prefer:**

All I know is I want this process to be *automatic*. Sure, I may be able to do something with a pre-commit hook, and inform collaborators about it. That said, I'd like it to be more automatic than that. Like, through GitHub Actions, and making it apply for pull requests too.

**Describe alternatives or workarounds you've considered:**

The alternative is an eventuality where the code is so stylistically inconsistent that readability will be negatively impacted, making it more difficult for everyone to troubleshoot and contribute to the project.

**Comment by 0x6c23** [comment]
Check out [super-linter](https://github.com/marketplace/actions/super-linter) or similar actions.

**Comment by reeseschultz** [comment]
super-linter looks good. Thanks for the recommendation.

Looks like strict linting is possible for pull requests from forks, but [formatting is not](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token). I'd like auto-formatting via GitHub Action, but it would be restricted to *internal* repository commits and pull requests only. We're left with semi-automated formatting, probably a pre-commit hook for that, but one which plays nice with whatever linter is used. This would necessitate a `CONTRIBUTING.md`, which is fine; I need to document the system flow for potential contributors anyway.

**Comment by reeseschultz** [comment]
Closing per #95.
