### ISSUE TITLE
Rename the ReeseUnityDemos repository

### ISSUE THREAD

**Issue by reeseschultz** [reeseschultz/ReeseUnityDemos#74]
**Is the improvement related to a problem? Please describe.**

The time has come. I've received comments that new users find the current name confusing. And I agree with them. Originally, this project featured some basic demos. Later, packages were created within `/Packages`, meaning that the project became a [monorepo](https://en.wikipedia.org/wiki/Monorepo). Mainly, the demos are secondary to the packages, because the demos show how to use the packages. (Since multiple packages are used together in the demos, they are not provided as "samples" on a per-package basis.)

**Describe the solution you'd prefer:**

I think I want to rename the repo to `ReeseUnityPackages`. Please respond to this issue if anyone has other ideas about this.

Anyway, I don't think putting monorepo in the name is appropriate, because many folks don't know what a monorepo is, nor do they care. Why should they? The point of it being a monorepo is really for my purposes as the maintainer. One major advantage of the monorepo is that I can update all the dependencies in one place. Alternatively, it would take 500 billion years to update projects separately in the editor. It also helps with *keeping* the packages consistently updated and devoid of deprecated code. This, however, is inconsequential to the average user who just wants stuff to work.

**Describe alternatives or workarounds you've considered:**

Simply not renaming the repo and letting new users be confused, which prevents the existing users from being confused. The existing users are important to me, but I'm sure they'll understand, especially because [GitHub will redirect from the old name indefinitely](https://github.community/t/how-long-does-github-forward-renamed-moved-repos/582/3) as long as I don't create a new repo of the same name as the old one.

**Additional context:**

This will blow up the project's presence on [OpenUPM](https://openupm.com/) without submitting a PR for it. But, #73 will require OpenUPM changes also, ~~and maybe being on that platform doesn't really matter when everything goes through Git URLs anyway?~~ **Edit:** After receiving user feedback, I will continue to support OpenUPM indefinitely because it makes updating packages easier for users.

**Comment by ptbarnaby** [comment]
The name change makes sense to me, it would just be worth making sure it's clear where to find the demos as the visibility on them will decrease when the repo is renamed. It would also be worth looking at update the package metadata to make it more obvious where it came from and where you can find demos/examples from with UPM

> maybe being on that platform doesn't really matter when everything goes through Git URLs anyway?

Personally I love the fact you've got packages on OpenUPM, it's good having a central repository for useful packages and I think it would be a shame for it to go away.

**Comment by reeseschultz** [comment]
> it would just be worth making sure it's clear where to find the demos as the visibility on them will decrease when the repo is renamed

I agree—I think the README needs to be updated to reflect where the demos are.

> It would also be worth looking at update the package metadata to make it more obvious where it came from 

Can you give me an example of that? I'm interested in doing anything I can to make things more obvious to the users.

> and where you can find demos/examples from with UPM

Are you referring to samples?

> Personally I love the fact you've got packages on OpenUPM, it's good having a central repository for useful packages and I think it would be a shame for it to go away.

I see you mentioned *why* you're using OpenUPM in #77, and I agree it makes sense to use for developer experience purposes. I didn't realize people were using it that way. My remark on that matter was admittedly flippant. I just add and remove Git URLs from my manifest file like a barbarian, and I forget that there are more civilized means of dependency management. :laughing:

**Comment by ptbarnaby** [comment]
> Can you give me an example of that? I'm interested in doing anything I can to make things more obvious to the users.

So for one thing you could set documentationUrl and changelogUrl in the package.json to point at the github URL, that way two of the links would take you to the right place (right now those links in UPM just error). I don't think you can use hyperlinks in the description unfortunately, but you could say "Click Documentation for example project" in the description and I think that would just make it a bit easier to jump from the UPM view to where the examples are. It's not ideal admittedly but hopefully Unity will extend UPM's preview a little more.

> Are you referring to samples?

I'm referring to the examples in https://github.com/reeseschultz/ReeseUnityDemos/tree/master/Assets/Scripts rather than the UPM Samples~ mechanism

**Comment by reeseschultz** [comment]
Okay, I can update the URLs and try to make things easier to locate within the package manager window. Thanks for the feedback.

**Comment by reeseschultz** [comment]
Closing per #95.
