### ISSUE TITLE
Incorporate hybrid nav agents in a "performance" demo

### ISSUE THREAD

**Issue by transcendtient** [reeseschultz/ReeseUnityDemos#80]
I'm very interested in DOTS and ECS... I hate the fact that its so hard to use them in conjunction with the tools everyone is used to using in Unity. So, I'm interested in the Hybrid setup specifically and the performance you can get with it.

Just thinking the demo would be much cooler if it had the option of spawning NavAgentHybrid since I'm about to spend the next some hours writing it myself.

**Comment by reeseschultz** [comment]
I recognize the value in your suggested enhancement. If you're going to make such a scene, you're welcome to submit a PR, adding the demo to this repository. I suppose you could also piggyback on an existing demo, and add a toggle for the functionality you seek via UI. Either way seems fine to me. Anyway, if you submit a PR, I'll be able to review it relatively quickly, assuming you don't change a lot of existing files/configuration.

**Comment by reeseschultz** [comment]
It seems like nobody is interested in implementing this feature, so I'm closing this issue. We can reopen the issue if someone has time to do it.
