### ISSUE TITLE
How can I let NavAgent Navigation in a larger area? where to modify it?

### ISSUE THREAD

**Issue by zlxt2714** [reeseschultz/ReeseUnityDemos#89]
When I was using your Reese.Nav, I encountered a problem. When the target point （NavDestination （WorldPoint））is far away, the agent does not move to the target point. How can I modify the settings and  where can find the settings file  ? Thank you for your answer

**Comment by reeseschultz** [comment]
Hi again. The [documentation explicitly covers how to override the default settings](https://github.com/reeseschultz/ReeseUnityDemos/blob/master/Packages/com.reese.nav/README.md#runtime-settings).

Specifically, it *sounds* like you want to increase the `PathSearchMax` over the default value provided. This is needed for very large maps.

Please let me know if this helps.
