### ISSUE TITLE
[BUG]NavPlanSystem use entityInQueryIndex and nativeThreadIndex together will cause bug

### ISSUE THREAD

**Issue by VincentSai** [reeseschultz/ReeseUnityDemos#93]
**Bug description:**

NavPlanSystem use entityInQueryIndex and nativeThreadIndex together will cause bug,
https://forum.unity.com/threads/nativethreadindex-and-entityinqueryindex-mixed-up-by-burst-compiler.1049879/

**Bug reproduction:**

Try Debug.Log entityInQueryIndex and nativeThreadIndex then will see they will be same number

**Expected behavior:**

entityInQueryIndex should be exactly entity sort key, nativeThreadIndex should be exactly thread index.

**Describe alternatives or workarounds you've considered:**

https://forum.unity.com/threads/nativethreadindex-and-entityinqueryindex-mixed-up-by-burst-compiler.1049879/
It is DOTS codegen's bug, so just like the post move nativeThreadIndex to last parameter with in.

**Comment by reeseschultz** [comment]
Closing per #95.
