### ISSUE TITLE
Adding the nav package errors due to math dependency

### ISSUE THREAD

**Issue by dolanmiu** [reeseschultz/ReeseUnityDemos#97]
When I try to install the nav library, it says I need math, but then I try to install math, it does not work

![image](https://user-images.githubusercontent.com/2917613/184557446-367a1e1b-8b52-4781-854f-c36e5a4fda17.png)

![image](https://user-images.githubusercontent.com/2917613/184557475-2fe8f2e2-1a5f-45cb-9907-5945138933ca.png)

## Dependencies here:

https://openupm.com/packages/com.reese.nav/?subPage=deps

## Installing it using the GIT way

This also gives an error too in Unity:

![image](https://user-images.githubusercontent.com/2917613/184557556-b30b1d8b-4a63-4fb4-b00b-e45db3f5071a.png)

**Comment by reeseschultz** [comment]
**Workaround:**

Try adding the packages in this order, via *add package from git URL*:

1. https://github.com/reeseschultz/ReeseUnityDemos.git#math
2. https://github.com/reeseschultz/ReeseUnityDemos.git#nav

This works in a new project I just tested for this purpose.

---

It's not ideal that the Unity editor is unable to resolve the `math` package from `nav` automatically. This is bad DX. I was under the mistaken assumption that this was working. @dolanmiu, thank you for thoroughly documenting the problem. I'll keep the issue open until this is adequately fixed.

**Comment by reeseschultz** [comment]
Closing, see #99 for more information.
