### ISSUE TITLE
[BUG] Package has invalid dependencies

### ISSUE THREAD

**Issue by Eskuchin** [reeseschultz/ReeseUnityDemos#98]
Hello! I'm very interested in pathfinding in DOTS, and your project looks very well put together, but I'm having trouble opening it. I'd appreciate any help!

**Bug description:**

Getting the following error in Unity:

 Project has invalid dependencies:
    com.unity.toolchain.linux-x86_64: Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.
  Package com.unity.sysroot.linux-x86_64@2.0.2 has invalid dependencies or related test packages:
    com.unity.sysroot (dependency): Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.
  Package com.unity.toolchain.linux-x86_64@2.0.2 has invalid dependencies or related test packages:
    com.unity.sysroot (dependency): Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.
    com.unity.sysroot.linux-x86_64 (dependency): Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.

**Bug reproduction:**

Downloaded the entire project as a zip and opened in Unity version 2021.3.4f1.

**Comment by reeseschultz** [comment]
Closing, see #99.
